<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1> Store </h1>
<h4> Подробная информация о товаре</h4>
<b> Название товара: </b> ${product.title} <br>
<b> Описание товара: </b> ${product.description} <br>
<b> Цена товара: </b> ${product.price} <br>
<b> Город: </b> ${product.city} <br>
<b> Автор: </b> ${product.author} <br>
<hr>
<h3> Создать новый товар</h3>
<form action="/product/delete/${product.id}" method="post">
    <input type="submit" value="Удалить товар"/>
</form>
</body>
</html>